[package]
name = "fluke-httpwg-server"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre = "0.6.3"
fluke = { version = "0.1.1", path = "../fluke" }
fluke-buffet = { version = "0.2.0", path = "../fluke-buffet" }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
