[package]
name = "fluke-curl-tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
fluke = { version = "0.1.0", path = "../../crates/fluke", features = ["maybe-uring-net"] }
curl = { version = "0.4.44", default-features = false, features = ["http2"] }
bytes = { version = "1.4.0", default-features = false }
pretty_assertions = { version = "1.3.0", default-features = false, features = ["std"] }
tokio-stream = { version = "0.1.14", default-features = false }
tracing-subscriber = { version = "0.3.17", default-features = false, features = ["std", "fmt", "ansi"] }
httparse = { version = "1.8.0", default-features = false, features = ["std"] }
tokio = { version = "1.28.2", default-features = false, features = ["io-util", "process", "time"] }
futures-util = { version = "0.3.28", default-features = false, features = ["std"] }
libc = "0.2.146"
eyre = { version = "0.6.8", default-features = false }
tracing = "0.1.39"
http = "0.2.9"
pretty-hex = "0.3.0"
