[workspace]
resolver = "2"
members = ["crates/*"]
exclude = ["crates/fluke-io-uring-async"]

[profile.dev.package."*"]
opt-level = 2

[profile.ci]
inherits = "dev"
opt-level = 1
lto = "off"

[profile.ci.package."*"]
opt-level = 2
