[package]
name = "httpwg-loona"
version = "0.2.0"
edition = "2021"
publish = false
authors = ["Amos Wenger <amos@bearcove.net>"]
description = """
A reference HTTP 1+2 server for httpwg, powered by loona
"""

[dependencies]
color-eyre = "0.6.3"
loona = { version = "0.2.0", path = "../loona" }
buffet = { version = "0.2.0", path = "../buffet" }
tracing = { version = "0.1.40", features = ["release_max_level_debug"] }
tracing-subscriber = "0.3.18"
