[package]
name = "fluke-tls-sample"
version = "0.1.0"
edition = "2021"
description = "A sample HTTPS proxy using fluke"
publish = false

[dependencies]
color-eyre = "0.6.2"
fluke = { path = "../../crates/fluke", features = ["maybe-uring-net"] }
rcgen = "0.10.0"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
rustls = { version = "0.21.7", features = ["secret_extraction"] }
tokio = { version = "1.28.2", features = ["full"] }
tokio-rustls = "0.24.1"
http = "0.2.9"
pretty-hex = "0.3.0"
socket2 = "0.5.3"

[target.'cfg(target_os = "linux")'.dependencies]
ktls = "3.0.0"
