name: h2spec-report

on:
  workflow_run:
    workflows: [test]
    types: [completed]

permissions:
  checks: write

jobs:
  h2spec-report:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        suite: [h2spec-generic, h2spec-hpack, h2spec-http2]
    steps:
      - name: Stub Git repo for test-reporter
        run: |
          git init
      - name: Publish h2spec-generic report
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: "${{ matrix.suite }}"
          artifact: "${{ matrix.suite }}"
          path: "target/${{ matrix.suite }}.xml"
          reporter: java-junit
