name: test

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

jobs:
  test-macos:
    env:
      CARGO_TERM_COLOR: always
    runs-on:
      - namespace-profile-macos-arm64
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Install Rust specified toolchain
        run: |
          rustc --version
      - uses: taiki-e/install-action@v2
        with:
          tool: just,cargo-nextest
      - name: Run tests
        run: |
          cd ${{ github.workspace }}
          just test
  test-linux:
    env:
      CARGO_TERM_COLOR: always
    runs-on:
      - namespace-profile-linux-amd64
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Setup cargo cache
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          path: |
            ./target
            ./target-cov
            ~/.cargo/git
            ~/.cargo/registry
            ~/.rustup
      - name: Install Rust specified toolchain
        run: |
          rustc --version
      - uses: taiki-e/install-action@v2
        with:
          tool: just,cargo-nextest,cargo-llvm-cov
      - name: Run tests
        run: |
          cd ${{ github.workspace }}
          cargo clippy
          just ci-test
      - name: Upload coverage information
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
          file: coverage/lcov.info
